### ISSUE TITLE
allow click outside to close with overlay

### ISSUE THREAD

**Issue by brenna** [yapplabs/ember-modal-dialog#101]
Would be nice have the `clickOutsideToClose` option available when there's an overlay. i.e. when true and `translucentOverlay` is also true, clicking on the overlay would close the modal.

**Comment by lukemelia** [comment]
@brenna seems reasonable. We would accept a PR for this.

**Comment by brenna** [comment]
@lukemelia cool, thanks. I'll see if i can get that hooked up.

**Comment by brenna** [comment]
This actually works as expected, I had an error in my implementation.
