### ISSUE TITLE
tether-dialog - renderInPlace css class not applied

### ISSUE THREAD

**Issue by pjmeadmtu** [yapplabs/ember-modal-dialog#102]
I'm using the tether-dialog in my project and trying to provide it relative position.  There's a class in  ember-modal-structures.scss `.ember-modal-dialog-in-place` but doesn't get applied when the `renderInPlace=true`.  Below is my tether-dialog setup.

{{#tether-dialog
    target=target
    close="toggle"
    hasOverlay=false
    renderInPlace=true
    targetAttachment="none"
    clickOutsideToClose=true
 }}

**Comment by chrislopresto** [comment]
@pjmeadmtu This appears to be working fine. Is the problem that the class selector isn't added? Or if it's just a styling issue, did you `@import "ember-modal-dialog/ember-modal-structure";` in `app.scss`?

![tether-dialog-in-place](https://cloud.githubusercontent.com/assets/93691/12191242/4e3516f6-b5a0-11e5-96b6-7a1d6b9d3a49.png)

**Comment by lukemelia** [comment]
I've verified this is working in 2.2.0
