### ISSUE TITLE
Introduction to ember-modal-dialog at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [yapplabs/ember-modal-dialog#105]
Hi there, would you someone familiar with the project would be open to giving an "Introduction to ember-modal-dialog" lightning talk at an upcoming Global Ember Meetup in the beginning of next year? We'll edit the video and give you video that you can embed into the addon's README. You can see an example of other introduction videos here https://vimeo.com/album/3607049

The talk usually covers:
1. What's use case for the addon?
2. How to get stated using it?
3. What should the user be aware of?

What do you think?

**Comment by lukemelia** [comment]
I nominate @chrislopresto!

**Comment by taras** [comment]
sweet :)

**Comment by chrislopresto** [comment]
Sounds good. I'm going to have to come up with a sweet backdrop for the video.

**Comment by taras** [comment]
nice! @chrislopresto I'm booking for January 16th or January 30th. What would you prefer?

**Comment by chrislopresto** [comment]
The 30th I suppose. No playoff football that weekend. (Nobody cares about the Pro Bowl.)

**Comment by taras** [comment]
I don't know what that is ;) Ok, consider yourself booked for the 30th

**Comment by chrislopresto** [comment]
This is on my calendar... looking forward to it. Closing here.
