### ISSUE TITLE
Overlay always dismisses modal

### ISSUE THREAD

**Issue by hmcq6** [yapplabs/ember-modal-dialog#106]
I want to make a modal with an overlay where clicking the overlay does not dismiss the modal. We use it as a way to confirm that a user is agreeing to some piece of information. The only way to dismiss the modal should be to click the big green button.

I also consider it to be inconsistent behavior that a modal with an overlay is dismissible by clicking outside the modal (on the overlay) despite the fact that clickOutsideToClose is false. If clickOutsideToClose is only relevant when you don't have an overlay then it should have a more specific name, like clickEmberModalDialogToClose or clickContainerToClose.

I suggest we remedy both situations by having clickOutsideToClose disable clicking the overlay to close. Making the behavior for clicking outside of the modal consistent whether the modal has an overlay or not.

If its decided that clickOutsideToClose should not be used to control clicking on the overlay then I suggest/request adding a new flag such as clickOverlayToClose.

I'm working on a PR to:
- [ ] add a new close action called clickOverlayToClose that will call the close action if clickOutsideToClose is true
- [ ] have the default template use clickOverlayToClose action instead of the default close action

**Comment by raycohen** [comment]
I don't think we need a new flag.  Adding the behavior you wanted the existing flag to provide seems reasonable.

You're using `clickOverlayToClose` as both a flag name and an action name.  I think the action that the template uses should become `clickedOverlay` and based on the value of the `clickOutsideToClose` flag it should either do nothing or send the `close` action.

**Comment by lukemelia** [comment]
This should be possible now. Let me know if it's not.
