### ISSUE TITLE
Ember 1.12 compatible release?

### ISSUE THREAD

**Issue by stickbyatlas** [yapplabs/ember-modal-dialog#112]
Hi there,

I'm eager to use this library, as it solves a dreaded pain-point in my project. I've been steadily upgrading an old codebase from Ember 1.9 through to 1.13. I'm currently stuck at version 1.12 with Ember CLI v0.2.7. According to your documentation, 1.12 shouldn't be a problem, but I can't get the application to build once I add ember-modal-dialog and ember-cli-sass.

As soon as I `ember install` those two libraries and try `ember server`, I get the following error on build:

```
EEXIST: file already exists, symlink '/.../my-app/node_modules/ember-modal-dialog/app/templates/components/modal-dialog.js' -> /.../my-app/tmp/template_compiler-output_path-1NcxZZ1M.tmp/my-app/templates/components/modal-dialog.js'
Error: EEXIST: file already exists, symlink '/.../my-app/node_modules/ember-modal-dialog/app/templates/components/modal-dialog.js' -> /.../my-app/tmp/template_compiler-output_path-1NcxZZ1M.tmp/my-app/templates/components/modal-dialog.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    ...
```

I don't know what is causing this failure, and after over a day of searching I can't find anything online that comes close to solving this error.

Here's the relevant dependencies from my `package.json`:
```
    "broccoli-asset-rev": "^2.0.1",
    "broccoli-sass": "^0.6.0",
    "ember-cli": "0.2.7",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-clock": "^1.0.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-cordova": "0.0.15",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-fastclick": "^1.0.3",
    "ember-cli-flot": "0.0.3",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.0.0-beta.18",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "ember-moment": "1.0.0",
    "emberx-slider": "1.0.3",
    "liquid-fire": "^0.19.0",
    "ember-intl": "1.2.2"
```

And here's my `bower.json`:

```
    "ember": "1.12.0",
    "ember-data": "1.0.0-beta.18",
    "ember-resolver": "~0.1.15",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.3",
    "ember-qunit-notifications": "0.0.7",
    "jquery": "1.11.3",
    "qunit": "~1.17.1",
    "ember-pouch": "~1.2.1",
    "fastclick": "~1.0.6",
    "flot": "~0.8.3",
    "ember-cli-moment-shim": "~0.0.3",
    "hammerjs": "~2.0.4",
    "ember-hammer": "~1.0.0",
    "howler": "~1.1.25"
```

I've tried a couple of earlier versions, but I get similar errors. I've `npm cache clean`ed and deleted `node_modules`, `bower_components` and `tmp`, then ran `npm install` and `bower install`, and the problem persists on a fresh app install.

At a glance, do you see anything that could be causing the failure to build described above? Is this error something others have encountered? Any guidance or advice you could provide would be appreciated at this point. I really, really don't want to roll my own modal dialog.

**Comment by stickbyatlas** [comment]
Update: I kept digging and discovered that, somehow, `modal-dialog.js` had found its way into my `app/components` folder (and `modal-dialog.hbs` found its way into my `app/templates` folder, which explains why the build script was giving me an EEXIST error. I deleted them both and the app started up again. However, I got a cryptic error : `... /app/styles/app.[scss|sass] does not exist`

I discovered that by adding ember-cli-sass into my package.json file was the culprit, as for some reason doubly-installing ember-cli-sass results in errors. See https://github.com/miguelcobain/ember-paper/issues/248 for what tipped me off. Perhaps you should include a note in your documentation that if ember-cli-sass is already installed in your project, you'll have problems getting the app to boot?

I've got a modal showing up in my application now. On to customization. Thanks for this great library!

**Comment by chrislopresto** [comment]
@stickbyatlas Thanks for digging and sharing. If you have time to take a stab at clarifying the SCSS documentation in our README, that would be great. Other folks have had problems in similar territory. If not, no worries. I'll take a pass alongside the next issue I dig into.
