### ISSUE TITLE
Off-center

### ISSUE THREAD

**Issue by ksnyde** [yapplabs/ember-modal-dialog#113]
I have a number of situations where I have a modal dialog box pop up and end up off-center (always to the right). I'm probably being a complete numpty but hoping that you can help. 

Here's the HTML from the browser (I've removed all CSS that might have interfered with the modal):

```
<div id="modal-overlays">
  <div class="ember-modal-wrapper ">
    <div id="ember1161" data-ember-modal-dialog-overlay="true" class="ember-modal-overlay translucent   ember-view">
      <div id="ember1162" class="ember-modal-dialog ember-modal-dialog-target-attachment-center   ember-view" style="left: 50%; top: 50%; margin-left: -334px; margin-top: -142px;">
        <div class="modal-header">
          <h2>Are you sure you want delete this job?</h2>
        </div>
        <div class="modal-body">
          <p>
            Deleting a job is permanent. An alternative might be re-download the files in this job and start over.
          </p>
          <p class="downer">
            <button id="ember1163" class="ember-view btn ui-button btn-default btn-lg delayed-hover">
              Yes
            </button>
            &nbsp;
            <button id="ember1164" class="ember-view btn ui-button btn-default btn-lg delayed-hover">
              No
            </button>
          </p>
        </div>

      </div>
    </div>
  </div>
</div>
```

Pretty stock, plain jane stuff. Here's a picture of the outcome:

![2016-01-16_16-27-14](https://cloud.githubusercontent.com/assets/980757/12373399/23cccc20-bc70-11e5-9e7a-5f7692bac53e.png)

**Comment by chrislopresto** [comment]
@ksnyde Can you share how you're using the `{{modal-dialog}}` component in your template along with any related controller/component code, CSS, etc? I'd be happy to take a look.

**Comment by ksnyde** [comment]
thanks for your attention @chrislopresto ...

I have two situations where I employ dialogs. Above you see an example of a fairly terse dialog box but in several other cases the dialog box has a lot of vertical and horizontal content so I've added the following CSS to ensure the modal dialog doesn't overwhelm the screen:

    .ember-modal-dialog {
      min-width: 65%;
      max-width: 75%;
      max-height: 80%;
    }

This does produce the desired effect in some regards (vertical & horizontal containment but not centering ... see linked video below) but still there is poor alignment on both the terse and verbose dialogs. I have noticed that the terse dialogs -- if I remove the above CSS -- seem to behave correctly. However, the verbose dialogs regardless of whether the CSS is there or not are shift to the right (and probably downward too but the vertical height overwhelms the screen so not easy to tell). 

Here's a video which demonstrates the before and after of the CSS: [modal-problem](https://vimeo.com/152682660). Password is "modal"

**Comment by ksnyde** [comment]
Some more info if it's helpful ... for the "short-form" modals here's the component I use to display them:

`are-you-sure.hbs`:

    {{#if model}}
      <div class="are-you-sure">
        {{#modal-dialog
          close=(action 'notSure')
          targetAttachment='center'
          translucentOverlay=true
        }}
        <div class="modal-header">
          <h2>{{model.heading}}</h2>
        </div>
        <div class="modal-body">
          <p>
            {{model.message}}
          </p>
          <p class='downer'>
            {{ui-button size='large' title=affirmative action=(action 'sure')}}
            &nbsp;&nbsp;
            {{ui-button size='large' title=negatory action=(action 'notSure')}}
          </p>
        </div>
        {{/modal-dialog}}
      </div>
    {{/if}}

Pretty plain jane I know but just wanted to assure you nothing crazy is going on.

**Comment by chrislopresto** [comment]
@ksnyde Thanks for the video and sample code. It's clear that our naive `positioned-container` component (used by the `modal-dialog` component) isn't doing the trick.

If you are willing and able to carry a dependency, a quick solution would be to `ember install ember-tether` and then change `{{modal-dialog}}` to `{{tether-dialog}}`. As a bonus, the modal would be able to reposition if/as the window size changes.

Regardless, I'd like to fix this issue. It would be nice to use a pure CSS solution, maybe using flexbox now that browser support is pretty good.

Thoughts?

**Comment by chrislopresto** [comment]
@ksnyde Also, I think #95 could explain the behavior you're seeing.

Are you able to isolate your case in a simple app we could collaborate on? I'd like to troubleshoot it.

**Comment by ksnyde** [comment]
- Hard to verify but #95 does seem like it could be talking to the same issue. 
- As for recreating it ... i can try but not sure hard it will be to pull out into a simplified app. 
- I do think your `flexbox` approach is a good idea though ... Bootstrap 4 is going that way which is a pretty good signal that Flexbox is a green light these days

Also, I have tried your suggestion of moving to `{{tether-dialog}}` and that does seem to fix my problem.

**Comment by sschadwick** [comment]
I was having a very similar issue modal opening on the right edge of the screen when it should be centered. My modal block was inside of a div classed 'modal'.

Solution was to change the class name.

**Comment by lukemelia** [comment]
The new css in use 2.2 should address this, too.
