### ISSUE TITLE
Rendering Link-to helpers inside the dialog changes the route, but doesn't close the modal.

### ISSUE THREAD

**Issue by angelosarto** [yapplabs/ember-modal-dialog#119]
In my use case the modal is attached to a navigation component (e.g. a "more links" pop-up).  Once open the user can navigate to other parts of the app - however since the modal's parent component does not re-render the modal stays open after a link-to route transition.

My solution was to use https://github.com/Kuzirashi/ember-link-action like this:

{{#link-to 'routeName' invokeAction='toggleModal'}} ... {{/link-to}}

Not sure if others have a use case where all link-to in a modal should close it, maybe could be a standard behavior.

**Comment by lukemelia** [comment]
@angelosarto thanks for sharing your solution. Closing a modal is entirely controlled by whether or not the modal is rendered by your template. So closing can happen by changing a boolean property that is being used as a guard, or by leaving a route whose template contains the modal. There's isn't anything special about link-to nor should there be from my perspective.

Besides the approach you took, you could also set the property that makes the modal hidden on your router's `willTransition` or `didTransition` hooks.
