### ISSUE TITLE
How about keeping targetModifier: null as default for tether-dialogs?

### ISSUE THREAD

**Issue by oscarni** [yapplabs/ember-modal-dialog#127]
I just spent a couple of hours trying to figure out why a `tether-dialog` would move automatically to be visible when scrolling sideways a mobile device.

At last I found that this addon sets `targetModifier: 'visible'` on the `ember-tether` component https://github.com/yapplabs/ember-modal-dialog/blob/b7f79649c940dd048edef94b4093425bb7acf510/addon/components/tether-dialog.js#L19 .

The default in ember-tether and hubspots tether is `null` https://github.com/yapplabs/ember-tether/blob/47b47b14d92eed3439c9b2c2f15347c19e0a133d/addon/components/ember-tether.js#L13 .

What do you think of updating this to the default `null` and letting us explicitly set it if one want the "visible"-behavior? Or at least mention it in the readme?

**Comment by chrislopresto** [comment]
@oscarni Thanks for the troubleshooting. I just perused the source for the latest Hubspot Tether release, made some changes to ember-tether and cut a new release... which enabled this fix for your issue: https://github.com/yapplabs/ember-modal-dialog/pull/128/commits/8595a0f767d7adef39edce3811954ee55f8b86d6

I'm about to merge https://github.com/yapplabs/ember-modal-dialog/pull/128 and cut a new ember-modal-dialog release that should do the trick.
