### ISSUE TITLE
Problem with subclassing

### ISSUE THREAD

**Issue by Crabar** [yapplabs/ember-modal-dialog#131]
I have next piece of code:

```
{{#if loginDialog}}
  {{#login-dialog}} Something! {{/login-dialog}}
{{/if}}
```

login-dialog.js:
```
import Component from 'ember-modal-dialog/components/modal-dialog';

export default Component.extend({

});
```
login-dialog.hbs
`{{yield}}`

And it just rendered to plain string "Something!" - without modal panel.
If I replace login-dialog for modal-dialog it works fine. Looks like some sort of bug, or I am do something wrong.

**Comment by chrislopresto** [comment]
@Crabar You will need to delete your `login-dialog.hbs` file. It's clobbering the default modal dialog template.

Let me know if this solves your problem.

**Comment by Crabar** [comment]
I'm guessing I have some misunderstaning with this addon. I thought I need just to extend from modal dialog to implement my custom modal dialog. But as I understand now, I need create my component as separate file and write next:

{{#if loginDialog}}
  {{#modal-dialog}}
    {{login-dialog}}
  {{/modal-dialog}}
{{/if}}

Am I right?

**Comment by chrislopresto** [comment]
Perhaps I misunderstood what you're trying to do. Are you trying to change the behavior of the modal dialog? Or are you just trying to customize the appearance? If you are only customizing the appearance, there is no need to subclass. Instead, you can just use the `{{modal-dialog}}` component in your own template just as you would use any component.

We have a bunch of usage examples here that may clarify things: http://yapplabs.github.io/ember-modal-dialog/?activeComponent=modal-dialog

**Comment by Crabar** [comment]
I want to create a modal dialog with a bunch of inputs etc. Now I got the idea at length =). So there are two ways for this: set {{modal-dialog}} as root element in my component's hbs or wrap component usage into {{modal-dialog}}. Thanks for help!

**Comment by mhluska** [comment]
@Crabar so how did you end up solving this in the latter case? Where do you specify the bunch of inputs if you can't how your own template?

**Comment by Crabar** [comment]
@mhluska 
Here is my implementation:
https://github.com/drinkit/ember-client/blob/master/app/templates/components/login-window.hbs
