### ISSUE TITLE
Routable modal without losing existing routes template

### ISSUE THREAD

**Issue by cjroebuck** [yapplabs/ember-modal-dialog#14]
Great addon guys, thanks for sharing.

I was wondering if there is anyway to have a routable modal which pops up over the currently existing routes template. 

Say if i'm at `/user` and I click a link or action which requires me to be logged in, I automatically redirect to `/login` and the login modal dialog pops up, but I want the template for the previous route to be still present underneath the modal. Right now it just gets wiped out and the modal is shown over a blank page, which kind of defeats the point of having the content in a modal to some degree?!

**Comment by raycohen** [comment]
The idea for using the route as a modal we mention in the README relies on the desired modal route being a subroute of the current route, and the current route having an `outlet`.  Imagine a "/posts/1/delete" route that shows a "are you sture you want to delete this post?" modal over "posts/1".

If you just had a "/login" route showing a modal, and you reloaded the page, you'd lose context for what to show under the modal.

**Comment by lukemelia** [comment]
You could use a query param to accomplish what you describe. It would be nice to have an example of this in our tests.
