### ISSUE TITLE
Using ember-modal-dialog within an addon

### ISSUE THREAD

**Issue by ynnoj** [yapplabs/ember-modal-dialog#143]
Is this currently possible? I've been unable to get this working.

See https://github.com/ember-cli/ember-cli/issues/3718.

**Comment by lukemelia** [comment]
@ynnoj we are using ember-modal-dialog 0.8.8 in an internal addon. What problem are you experiencing? If you put together a repo demonstrating the problem, I'd be happy to help debug.

**Comment by ynnoj** [comment]
@lukemelia I got it figured out, thank you! 😄
