### ISSUE TITLE
targetAttachment doesn't work with Glimmer 2

### ISSUE THREAD

**Issue by Dhaulagiri** [yapplabs/ember-modal-dialog#145]
In ember 2.9.0-alpha.2 positioning a modal via `targetAttachment` doesn't work because on `didInsertElement` [here](https://github.com/yapplabs/ember-modal-dialog/blob/0ed8bb7f03033e7e47e21be148038f189ea2cb85/addon/components/positioned-container.js#L29-L31) `this._state` is `hasElement` causing the positioning logic that follows not to run.

**Comment by sly7-7** [comment]
This is still an issue in 2.9.0.beta.2 but I think this will be resolved in the next release. This was fixed in https://github.com/emberjs/ember.js/pull/14300.

**Comment by Dhaulagiri** [comment]
@sly7-7 yep, I confirmed against latest canary that this problem no longer exists.  Thanks for pointing this out!
