### ISSUE TITLE
How to test in a component unit test

### ISSUE THREAD

**Issue by varblob** [yapplabs/ember-modal-dialog#15]
I'm using modal-dialog in a component test and it's currently bombing on 

Cannot read property 'appendChild' of null
    at DOMHelper.prototype.appendMorph (http://localhost:4200/assets/vendor.js:13401:14)
    at render (http://localhost:4200/assets/vendor.js:118128:32)
    at superWrapper [as render] (http://localhost:4200/assets/vendor.js:28135:20)
    at EmberRenderer_createElement [as createElement] (http://localhost:4200/assets/vendor.js:49416:14)
    at EmberRenderer.Renderer_renderTree [as renderTree] (http://localhost:4200/assets/vendor.js:18978:22)
    at http://localhost:4200/assets/vendor.js:51886:24
    at Queue.invoke (http://localhost:4200/assets/vendor.js:11420:18)
    at Object.Queue.flush (http://localhost:4200/assets/vendor.js:11485:13)
    at Object.DeferredActionQueues.flush (http://localhost:4200/assets/vendor.js:11290:19)
    at Object.Backburner.end (http://localhost:4200/assets/vendor.js:10715:27)

I'm wondering if it's because the wormhole target doesn't exist in a unit test.  Any thoughts on how one may go about working around this issue?

**Comment by varblob** [comment]
I think this is just a case of initializer not getting run.  I'm closing this and will post a new issue for added document once I figure this out.  Sorry for noise.

**Comment by lukemelia** [comment]
The initializer should not run in a unit test, but the target div does need to exist.

**Comment by varblob** [comment]
I figured out a work around.  I'm pretty sure there must be a better way.

    import initialize from 'ember-modal-dialog/initializers/add-modals-container'

    moduleForComponent('component-that-uses-modal-dialog', {
      needs: [
        'component:modal-dialog',
        'component:ember-modal-dialog-positioned-container',
        'component:ember-wormhole'
      ]
    });

    test("don't crash please", function(assert){
      initialize(this.container,{
       rootElement: '#ember-testing',
       register: this.container.register,
       inject: this.container.injection
      });
    });

**Comment by varblob** [comment]
Hmm without running the initializer would the desire then to be to do the things the initializer does but not via the initializer?

Something like create the div for the modal to live in, in setup and then inject destinationElementId into component:modal-dialog.

**Comment by lukemelia** [comment]
@varblob yes, exactly as you describe

**Comment by varblob** [comment]
this is what I ended up with based on your suggestions. 

  import initialize from 'ember-modal-dialog/initializers/add-modals-container'

  moduleForComponent('component-that-uses-modal-dialog', {
    beforeEach: function(){
      modalContainerEl = document.createElement("div")
      modalContainerEl.id = 'modal-overlays'
      rootEl = document.querySelector("#ember-testing")
      rootEl.appendChild(modalContainerEl)
      this.container.register('config:modals-container-id', 'modal-overlays', instantiate: false)
      this.container.injection('component:modal-dialog', 'destinationElementId', 'config:modals-container-id')
    },
    needs: [
      'component:modal-dialog',
      'component:ember-modal-dialog-positioned-container',
      'component:ember-wormhole'
    ]
  });

If this looks reasonable I can submit a pull request to the documentation sometime this week.

**Comment by lukemelia** [comment]
@varblob Yes, that would be great. Maybe we can add such a component to the dummy app, and include a test, too. Then we can reference it from the README. Thanks!
