### ISSUE TITLE
Cannot dismiss route modal by clicking outside modal

### ISSUE THREAD

**Issue by hvgotcodes** [yapplabs/ember-modal-dialog#150]
I could not create an ember twiddle for this but created a bare project for it.  I did the following.
1.  Generate route "modal" (url localhost:4200/modal}
2. application.hbs

```
{{#link-to "modal"}}Link to route with modal{{/link-to}}
{{outlet}}

```
1. modal.hbs

```
Modal Route

{{#modal-dialog clickOutsideToClose=true}}
    Oh hai there!
{{/modal-dialog}}
```

When I click the link in application template the app transitions the route and the modal appears.  However clicking outside the modal does not dismiss the modal nor return me to the previous route.  

I'm not sure if you consider this a bug.  Having the ability to dismiss by clicking outside the modal would be nice (returning to the parent route).  

Note, If I add a link back to index in the modal, and click that, the modal does dismiss.

**Comment by ryanlabouve** [comment]
I was doing a little investigation and it looks like there is a PR to address this: https://github.com/yapplabs/ember-modal-dialog/pull/103

**Comment by Redsandro** [comment]
No rush. :joy:

**Comment by lukemelia** [comment]
As of 1.0.0, this can now we implemented by using an overlay and the new `onClickOverlay` action.
