### ISSUE TITLE
Modal as child of the index route

### ISSUE THREAD

**Issue by jrburke** [yapplabs/ember-modal-dialog#156]
Using Ember 2.8.2 and latest ember-modal-dialog.

Is it possible to show an ember-modal-dialog over an index route's contents?

I have a posts route that has some nested routes, and an index template.hbs file. The template.hbs shows the list of posts. The routes are set up like this:

```javascript
this.route('posts', function () {
    this.route('new');

    this.route('post', { path: ':post_id' }, function () {
        ...
    });
});
```

I would like the "new" route to be an ember-modal-dialog that is displayed over the list of posts from the index template.hbs. However, since the "new" route is a sibling to the implicit "index" route, when I go to "new", the list of posts disappear.

I tried this, but an Ember runtime error about Unrecognized URL or route, forget the exact wording at the moment:

```javascript
this.route('posts', function () {
    this.route('index', function () {
        this.route('new');
    });

    this.route('post', { path: ':post_id' }, function () {
        ...
    });
});
```

I am also new to Ember so this could be my misunderstanding of routes in Ember, any pointers are appreciated.

**Comment by lukemelia** [comment]
@jrburke I believe you could use the "slash" route to accomplish this.

```js
this.route('posts', function () {
    this.route('list', { path: '/' }, function () {
        this.route('new');
    });
    this.route('post', { path: ':post_id' }, function () {
        ...
    });
});
```
