### ISSUE TITLE
Tap outside to close

### ISSUE THREAD

**Issue by samselikoff** [yapplabs/ember-modal-dialog#158]
`clickOutsideToClose` is wired up here — 
https://github.com/yapplabs/ember-modal-dialog/blob/8a8f26219e94a5e194c94e5aeac5e0153da88d1e/addon/components/modal-dialog.js#L64

Could we make this trigger for `touch` events too? I think it's a reasonable default and we don't need to add any additional API.

**Comment by lukemelia** [comment]
No objections here.

**Comment by Chee7ah** [comment]
#161

**Comment by lukemelia** [comment]
Closed since #161 has been merged.
