### ISSUE TITLE
Are closure actions supported?

### ISSUE THREAD

**Issue by lucasdetoledo** [yapplabs/ember-modal-dialog#163]
Passing in properties works perfectly (isModalActive, selectedPatients and selectedPatientComponent all trickle down correctly), when I attempt to pass in a method defined in the actions map, and try to retrieve it from within the model, it returns undefined. Of course, there may be a bug in my code somewhere, but after spending some hours looking at this I must ask: are closure actions supported?

```
  {{#modal-dialog close='toggleIsModalActive'
    translucentOverlay=true
    attachment='top center'
    targetAttachment='top center'
    container-class='patient-modal-container'
    isModalActive=isModalActive
    selectedPatient=selectedPatient
    selectedPatientComponent=selectedPatientComponent
    a=(action 'a')}}
    {{patient-modal-navbar isModalActive=isModalActive
      selectedPatient=selectedPatient
      a=a}}
  ...
  }}
```

So 'a', is undefined in patient-modal-navbar.

Thank you kindly.

**Comment by lukemelia** [comment]
Hi @lucasdetoledo, closure actions are indeed supported as anywhere else in ember. The way that blocks and lexical scoping works in Ember templates is the explanation for why `a` is undefined in your example. Ember will try to resolve `a` against this template's scope, not the modal-dialog component's scope. So the following would be more appropriate:

```js
  {{#modal-dialog close='toggleIsModalActive'
    translucentOverlay=true
    attachment='top center'
    targetAttachment='top center'
    container-class='patient-modal-container'
    isModalActive=isModalActive
    selectedPatient=selectedPatient
    selectedPatientComponent=selectedPatientComponent}}
    {{patient-modal-navbar isModalActive=isModalActive
      selectedPatient=selectedPatient
      a=(action 'a')}}
  ...
  }}
```

I hope that helps!

**Comment by lucasdetoledo** [comment]
Lukemelia, thank you!
