### ISSUE TITLE
Doesn't work with custom fonts

### ISSUE THREAD

**Issue by rwwagner90** [yapplabs/ember-modal-dialog#17]
If you update the fonts, it calculates the size incorrectly, thus making the positioning off. Probably need to wrap in some sort of font loader.

**Comment by chrislopresto** [comment]
@rwwagner90 The 0.7.x releases use our new ember-tether addon for positioning. This might address the problem. Mind trying again with the latest release?

If it doesn't do the trick, then some additional context, screenshots, etc. could help. Let us know.

**Comment by rwwagner90** [comment]
Did you add anything pertaining to fonts? It's a font loader issue.

**Comment by rwwagner90** [comment]
It calculates the size of the box based on the unstyled font, which means the size of the box is wrong and therefore throws off positioning.

**Comment by lukemelia** [comment]
@rwwagner90 Tether.js, which ember-tether uses, has more sophisticated repositioning logic, so yes, the hope is that by using ember-modal-dialog with ember-tether, the fontloader issue you described will be addressed.

**Comment by rwwagner90** [comment]
This is a very old issue now. Going to close, as I have no time to fix it, and it doesn't seem to be a big issue for anyone.
