### ISSUE TITLE
Question: about multiple instances of the same ember app

### ISSUE THREAD

**Issue by franktcurran** [yapplabs/ember-modal-dialog#176]
We have a large, non-ember, application that contains instances of our various ember apps. The same ember app can appear multiple times, getting a unique element id like so:
```
...
<div id="our-ember-app-1" class="ember-application">
   <div id="ember608" class="ember-view">
      <blahblahblah/>
   </div>
</div>
...
<div id="our-ember-app-2" class="ember-application">
   <div id="ember608" class="ember-view">
      <blahblahblah/>
   </div>
</div>
...
```
The problem we started noticing with modals, was if the second (and on) application to load created a modal, the modal overlay would be added to the first application to load.
```
...
<div id="our-ember-app-1" class="ember-application">
   <div id="modal-overlays">
      <blahblahblah/>
   </div>
   <div id="ember608" class="ember-view">
      <blahblahblah/>
   </div>
</div>
...
<div id="our-ember-app-2" class="ember-application">
   <div id="ember608" class="ember-view">
      <blahblahblah/>
   </div>
</div>
...
```
I attempted to set the target to `our-ember-app-2`, but the modal overlay was still being added to `our-ember-app-1`. Should target allow me to target the second (or whatever) ember app in this way or is there another way to do this? Let me know if I'm not being clear or you need more information to be able to help. Thanks!

**Comment by lukemelia** [comment]
I'm not sure if it would work, but have you tried configuring one of the instances to have a different modal root element ID? (See https://github.com/yapplabs/ember-modal-dialog#configuring-the-modal-root-element-id). Feel free to PR if there are rough edges that don't quite work with this solution. You may well be the first person trying to do this.

**Comment by franktcurran** [comment]
@lukemelia, thanks for the suggestion! I gave that approach a go - definitely set it up correctly with a single instance, but with how our ember apps are loaded into our application, it seems like the config is overwritten, or the last one is taken, so I still get "modal-overlays". At least, that's what I think is happening. Thanks again for the help! I'll continue to look into it and if I find a solution that might be reusable for others I'll update this ticket.

**Comment by franktcurran** [comment]
A coworker of mine took a look at this with me. I thought I had been setting the renderInPlace config, but it turns out I wasn't... Thanks again for you help @lukemelia.
