### ISSUE TITLE
Unchecked access to `ENV['ember-modal-dialog'][prop]` breaks ember-twiddle

### ISSUE THREAD

**Issue by jacobq** [yapplabs/ember-modal-dialog#198]
I don't know if it's fair to blame `ember-modal-dialog` for this, as it only applies to use with [ember twiddle](https://ember-twiddle.com/), but since it used to work and then stopped working I thought I ought to at least file an issue for others to discover if they wind up in the same situation.

Ember Twiddle evidently doesn't generate the application configuration / environment the same as ember-cli, so even though a twiddle can have the `ember-modal-dialog` addon installed, it doesn't seem to run its `environment.js` file, setting `appConfig['ember-modal-dialog']['hasLiquidWormhole']`, etc. So when the app tries to run, as soon as it tries to render `{{#modal-dialog}}...` it blows up with an error in the console similar to one shown below. This appears to be caused by [this line (`return ENV['ember-modal-dialog'][prop]`)](https://github.com/yapplabs/ember-modal-dialog/blob/11570d49d4faaf40a16484c2c4452d7e5c204170/app/services/modal-dialog.js#L8).

```
_twiddleConfigEnvironment.default['ember-modal-dialog'] is undefined
computedFromConfig/<@https://addons.ember-twiddle.com/ember-2.12.0/ember-modal-dialog/2.2.0/addon.js:1753:7
ComputedPropertyPrototype.get@https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:17389:15
get@https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:22382:14
_getPath@https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.12.0/ember.debug.js:22403:13"
...
```

To work around this I manually edited the `twiddle.json` file to include the snippet below:

```
  "ENV": {
  	"ember-modal-dialog": {
    	    "hasLiquidWormhole": "2.0.5",
    	    "hasLiquidTether": "2.0.4",
    	    "hasEmberTether": "1.0.0-beta.0"
  	}
  },
```

**Comment by jacobq** [comment]
Here's a link to a twiddle demonstrating the work-around: https://ember-twiddle.com/ff9ff22445f6215d4f238f6c35e2d4bc

**Comment by jacobq** [comment]
Thanks!

**Comment by lukemelia** [comment]
Thanks to you @jacobq!
