### ISSUE TITLE
Animating with liquid-fire `explode` does not work

### ISSUE THREAD

**Issue by jacobq** [yapplabs/ember-modal-dialog#199]
Per https://github.com/yapplabs/ember-modal-dialog/issues/194#issuecomment-301782289 I took a look at the [code in `tests/dummy`](https://github.com/yapplabs/ember-modal-dialog/blob/master/tests/dummy/app/transitions.js). However, when I try to animate the overlay and dialog elements separately as shown there it doesn't work right--there is a second copy / ghost element that appears during part of the transition. (Perhaps this is because one element contains the other?) 

Perhaps I'm just doing something wrong, but I thought I was doing basically the same thing as the test shows. See example here: https://ember-twiddle.com/ff9ff22445f6215d4f238f6c35e2d4bc

```
const options = {duration: 2000, easing: 'easeInOutQuad'};

export default function(){
  this.transition(
    //this.use('fade')	// this works
    
    // this has a glitch; can see second copy/ghost of modal in top left when closing
    this.use('explode', {
      pick: '.ember-modal-overlay',
      use: ['fade', options]
    }, {
      pick: '.ember-modal-dialog',
      use: ['fade', options]
    })    
  );
};
```

![twiddle-fade-emd-problem2](https://user-images.githubusercontent.com/1633459/27062280-a57b664a-4faf-11e7-8d30-b154236b54c2.png)

**Comment by billdami** [comment]
I've noticed this same behavior in my own app. It seems as though liquid-fire is not properly keeping the modal element out of view before it animates it.

**Comment by jacobq** [comment]
I don't think the fault is with liquid-fire since it is animating the elements that it is given. The problem seems to be that we are trying to animate the wrapper and modal separately but they are not independent: the modal is a child of the wrapper.

**Comment by billdami** [comment]
@jacobq You were right, and this is the secret sauce we were missing I think:

```
overlayPosition="sibling"
```
I added that, and now it works perfectly. 🎉 Imo that should probably be noted somewhere in the documentation for the `animatable` configuration.

**Comment by jacobq** [comment]
Ah, thank you for discovering that. I tried it in the twiddle and it looks much better. Later I will try in my own code. I will close this since this seems to resolve the problem. Since there's an open issue for improving docs and there's a link back to here from there I don't think more reminders are needed.
