### ISSUE TITLE
Using modal in #each

### ISSUE THREAD

**Issue by lsim6580** [yapplabs/ember-modal-dialog#212]
I have the following Setup: I have several movies and those movies contain several trailers

![untitled](https://user-images.githubusercontent.com/15107393/28803882-452d5cac-7625-11e7-9e3a-8d651cb40441.png)

Please forgive me as I am new to ember, but it looks like the "movie" object is not being passed to the modal. I have tried with both with/out the ember carousel helper

**Comment by lukemelia** [comment]
Hi @lsim6580, I don't see any reason this would be related to ember-modal-dialog. I hope you got this resolved!
