### ISSUE TITLE
Make onClose work with route names

### ISSUE THREAD

**Issue by zacstewart** [yapplabs/ember-modal-dialog#219]
I'm using the `modal-dialog` component in it's own route. I can wire up actions in the route to `transitionTo` the parent route upon clicking the overlay, and I have a cancel button that is just a `link-to` the parent.

It seems like it would be natural to have a way to transition to a specified route instead of needing this boilerplate.

**Comment by samselikoff** [comment]
I think you can just do it in HBS:

```hbs
{{#modal-dialog onClose=(transition-to 'route')}}
```
