### ISSUE TITLE
Custom modals don't have destinationElementId injected

### ISSUE THREAD

**Issue by rlivsey** [yapplabs/ember-modal-dialog#22]
In our app we have some modals which are "full screen" and have some custom behaviour/settings (no overlay, different CSS etc…).

To accomplish this I made a new component which extends from `ModalDialogComponent` add adds in the custom behaviour so in my templates I can now do:

```hbs
<full-screen-modal>
    modal contents here
</full-screen-modal>
```

This breaks because the wormhole's destination element ID is only [injected into the 'modal-dialog' component](https://github.com/yapplabs/ember-modal-dialog/blob/5802c696333718f7b1268d40962b8a8974c4e688/addon/initializers/add-modals-container.js#L13-15).

This is easily worked around by adding another injection:

```javascript
export default {
  after: 'add-modals-container',
  name: 'custom-modals',
  initialize(_, application) {
    application.inject('component:full-screen-modal',
                       'destinationElementId',
                       'config:modals-container-id');
  }
};
```

However, ideally we wouldn't have to do this.

**Comment by lukemelia** [comment]
Interesting. We could get around this by creating a service to hold the default destinationElementId that is accessed via  `Ember.inject.service`, so that subclasses will have access to it. Will noodle on this and open to other folks' feedback.

**Comment by truenorth** [comment]
I found the same problem, and had to resort to the same solution https://github.com/sgasser/ember-cli-materialize/blob/master/app/initializers/add-modals-container.js#L12-L14

**Comment by sandstrom** [comment]
Same issue here, same workaround. `Ember.inject.service` sounds like a good idea!

**Comment by lukemelia** [comment]
OK, sounds like a plan. Open to a PR if someone wants to take this on.

**Comment by rlivsey** [comment]
@lukemelia I'm doing this in a pop-over addon for our app, using [a service which just has one property](https://github.com/minutebase/mb-pop-over/blob/e1d51490400cf08f1a7bf43ca66e7ee392000760/app/services/pop-over.js) holding the `destinationElementId`, that property is [set from the initializer](https://github.com/minutebase/mb-pop-over/blob/e1d51490400cf08f1a7bf43ca66e7ee392000760/app/initializers/add-container.js) and then used in [the component](https://github.com/minutebase/mb-pop-over/blob/e1d51490400cf08f1a7bf43ca66e7ee392000760/app/components/pop-over-body.js#L14).

If that looks good, I can do the same here and will open a pull request later today.

**Comment by lukemelia** [comment]
@rlivsey Sounds good to me. Thanks. Please update the docs with your PR, as I think this approach is a little more confusing, but clearly necessary given the feedback.
