### ISSUE TITLE
Running without jquery

### ISSUE THREAD

**Issue by kellyselden** [yapplabs/ember-modal-dialog#227]
Are you interested in tracking this effort? I tried to go without jQuery in our app (we aren't using it directly), but the remaining console error was from here.

**Comment by lukemelia** [comment]
Yes, very open to this.

**Comment by kellyselden** [comment]
For anyone that wants to take this on, from [here](https://github.com/thefrontside/emberx-select/issues/199#issuecomment-344356672):

> This is a pretty good guide, although slightly outdated by now http://miguelcamba.com/blog/2017/04/11/the-future-of-embers-testing-and-the-beheading-of-jquery/

> There is a section at the bottom on how to update an addon. It involves using the new jquery-free test helpers (codemod available I believe), and some ember-try fixing for older ember versions. This also helps a lot https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-jquery.md.
