### ISSUE TITLE
Changing container-class to containerClass to avoid deprecation

### ISSUE THREAD

**Issue by m-nagy** [yapplabs/ember-modal-dialog#228]
After upgrading to Ember 2.16.x a deprecation warning appears as following:
```Passing `container-class` (kebab-case) is deprecated in favor of `containerClass` (camelCase). Will be removed in 3.0.0. [deprecation id: ember-modal-dialog.kebab-props]```

**Comment by nmcclay** [comment]
This continues to be a warning in Ember 2.18, are there any plans to update this issue?

**Comment by lukemelia** [comment]
This is by design. This deprecation is part of ember-modal-dialog.
