### ISSUE TITLE
Error: Could not find module `@ember/object` imported from `my-app/services/modal-dialog`

### ISSUE THREAD

**Issue by charneykaye** [yapplabs/ember-modal-dialog#231]
I'm currently stumped trying to solve this error, which came up after merging some work done a few months ago. I upgraded Ember since then, to 2.16, and have now upgraded ember-modal-dialog to 2.4.0.

It's dying on **./node_modules/ember-modal-dialog/app/services/modal-dialog.js** line 1:
```
import { computed } from '@ember/object';
```

I was running Node v7.10.1 so I upgraded to v8.9.1

Any ideas? Thanks!

```
loader.js:247 Uncaught Error: Could not find module `@ember/object` imported from `my-app/services/modal-dialog`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:392)
    at Class.resolveOther (index.js:113)
    at Class.superWrapper [as resolveOther] (ember.debug.js:23110)
    at Class.resolve (ember.debug.js:5870)
    at resolve (ember.debug.js:2445)
```

**Comment by lukemelia** [comment]
What version of ember-cli and ember-cli-babel do you have? I think that is what enables this import syntax. @Dhaulagiri may have further insight for you.

**Comment by charneykaye** [comment]
Thanks @lukemelia nailed it with upgrading ember-related packages. To the credit of the entire Ember community, I was able to perform all of these npm package upgrades at once:

Package | From | To
--------|------|------
broccoli-asset-rev | ^2.4.2 | ^2.6.0
ember-ajax | 2.5.6 | 3.0.0
ember-basic-dropdown | ^0.31.3 | ^0.34.0
ember-cli | ^2.13.0 | ^2.16.0
ember-cli-babel | ^5.2.1 | ^6.10.0 
ember-cli-dependency-checker | ^1.2.0 | ^2.1.0 
ember-cli-flash | 1.4.2 |  1.5.0 
ember-cli-htmlbars | ^1.0.3 | ^2.0.3 
ember-cli-htmlbars-inline-precompile | ^0.3.1 | ^1.0.2 
ember-cli-inject-live-reload | ^1.6.1 | ^1.7.0 
ember-cli-sass | 6.1.2 | 7.1.1 
ember-cli-showdown | ^3.1.1 | ^4.1.0 
ember-cli-string-helpers | ^1.4.0 | ^1.5.0 
ember-cli-test-loader | ^2.1.0 | ^2.2.0 
ember-cli-uglify | ^1.2.0 | ^2.0.0 
ember-cookies | 0.0.13 | 0.1.2 
ember-crumbly | 1.0.6 | 1.0.7 
ember-data | ^2.13.0 | ^2.16.0 
ember-font-awesome | ^3.0.5 | ^4.0.0-alpha.14 
ember-message-bus | 0.3.3 | ^0.3.6 
ember-modal-dialog | ^2.3.0 | ^2.4.0 
ember-moment | 7.3.0 | ^7.5.0 
ember-power-select | 1.7.0 | ^1.10.3 
ember-resolver | ^4.1.0 | ^4.5.0 
ember-route-action-helper | ^2.0.2 | ^2.0.6 
ember-simple-auth | 1.2.2 | ^1.4.0 
ember-truth-helpers | 1.3.0 | ^2.0.0 
loader.js | ^4.1.0 | ^4.6.0

**Comment by Dhaulagiri** [comment]
@charneykaye i'm guessing you would have had this issue until you updated ember-cli-babel.  This should not have happened so I opened #232 to avoid trolling others with this.

**Comment by charneykaye** [comment]
Thanks @Dhaulagiri
