### ISSUE TITLE
Breaks within an engine

### ISSUE THREAD

**Issue by denzo** [yapplabs/ember-modal-dialog#233]
When this addon is a dependency of the engine the initializer throws an error as `App.rootElement` is `undefined`. This is because `App` in the initializer of the engine is `Engine`.

https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/initializers/add-modals-container.js#L31

**Comment by swarnavallis** [comment]
is this solved @denzo

**Comment by samselikoff** [comment]
@swarnavallis don't believe so, and looks like nobody else is really on it. If you're in a spot where you need it I'd encourage you to try to fix it!

**Comment by romgere** [comment]
:wave: Any workaround about this issue ? I tried to find one on my side but I'm stuck...
I tried to find a way to access to the application instance inside the engine initializer, but I failed :disappointed:

**Comment by buschtoens** [comment]
Submitted a fix: #315
