### ISSUE TITLE
clickOutsideToClose is not work in ember 2.18 

### ISSUE THREAD

**Issue by 85636682** [yapplabs/ember-modal-dialog#239]
clickOutsideToClose is not work in ember 2.18 
i clicked the modal's outside is not close..
```
ember 2.18
ember-modal-dialog 2.4.1
```

**Comment by philipdesmedt** [comment]
Is there any workaround or update on this issue?

**Comment by lukemelia** [comment]
This should be fixed in 3.0.0-beta.0. Please give it a try and let me know.

**Comment by slannigan** [comment]
Yes, it's working in 3.0.0-beta.0 👍

**Comment by vishwasraj-thyagaraj** [comment]
@lukemelia `clickOutsideToClose`  does not work in 3.0.0-beta.4

**Comment by IBRAHIMDANS** [comment]
clickOutsideToClose not work in 4.1.2
