### ISSUE TITLE
Close when user clicks off modal (on overlay)

### ISSUE THREAD

**Issue by pzuraq** [yapplabs/ember-modal-dialog#24]
Is there a way to do this already? If not we can add it pretty quickly, seems like pretty general behavior.

**Comment by lukemelia** [comment]
Yes, it's easy to do today. See the examples in the dummy app to learn how.

**Comment by oskarrough** [comment]
Where exactly is it in the dummy app? I couldn't find it. Thank you!

**Comment by theworkerant** [comment]
@oskarrough You're right this was hard to find: https://github.com/yapplabs/ember-modal-dialog/blob/abb32b06702c91f1fa5a5aa99c889dfa545920c9/addon/templates/components/modal-dialog.hbs#L3

If you want to override this sucker, look here: https://github.com/yapplabs/ember-modal-dialog/blob/abb32b06702c91f1fa5a5aa99c889dfa545920c9/addon/components/modal-dialog.js#L48

And do something similar as suggested in the [README for Keyboard Shortcuts](https://github.com/yapplabs/ember-modal-dialog/blob/abb32b06702c91f1fa5a5aa99c889dfa545920c9/README.md#keyboard-shortcuts)

**Comment by lukemelia** [comment]
@theworkerant / @oskarrough sorry this was tough to understand. Can one of you submit a PR that would make it easier to grok for a developer new to the project?

**Comment by pzuraq** [comment]
@lukemelia I think the issue is that the documentation doesn't clearly specify how the close action is triggered, I made a PR to fix that. If the close action is sent from other places besides clicking the overlay let me know, I can clarify further.

**Comment by oskarrough** [comment]
Thank you, helped me!
