### ISSUE TITLE
Lazy Loading modal content?

### ISSUE THREAD

**Issue by lougreenwood** [yapplabs/ember-modal-dialog#249]
Is there any suggested method for lazy loading modal content?

My app has a bunch of modals containing forms (for creating new records of various types).

It seems wasteful to create all of these forms in the DOM when in most use cases they're not needed.

Thanks! :)

**Comment by lukemelia** [comment]
@lougreenwood no DOM is created until a modal is shown. If you are concerned with lazy loading the underlying code, you could roll your own with https://github.com/ember-engines/ember-asset-loader, but there's nothing built into ember-modal-dialog, and I think it's out of scope for this addon.

**Comment by lougreenwood** [comment]
Cool - thanks for the `ember-asset-loader` tip 👍
