### ISSUE TITLE
Deprecation raised with ember 3.4

### ISSUE THREAD

**Issue by sly7-7** [yapplabs/ember-modal-dialog#262]
Since ember 3.4, there is a new deprecation warning when using sendAction() https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-component-send-action.

I'm not sure if we could just replace it with actually calling the actions.

**Comment by jdurand** [comment]
We could simply replace `sendAction` with a function call, but this would break the implementation suggested in the README.
Developers would need to pass in closure actions instead of an action's name :

```
{{#modal-dialog onClose=(action "toggleModal") ... }}
```

**Comment by sly7-7** [comment]
Seems like fixed in 3.0.0.beta.2 Thanks @lukemelia ❤️

**Comment by lukemelia** [comment]
Thanks for confirming @sly7-7 👍
