### ISSUE TITLE
Deprecation Warnings On 3.8+

### ISSUE THREAD

**Issue by benkiefer** [yapplabs/ember-modal-dialog#275]
Started upgrading projects to the latest LTS this morning, and ran into the following deprecation warning for projects using ember-modal-dialog.

https://deprecations.emberjs.com/v3.x/#toc_computed-property-override

https://github.com/yapplabs/ember-modal-dialog/blob/399dc67c8a220505f0631845872280f24b88e32d/addon/components/modal-dialog.js#L17 appears to be the issue.

**Comment by benkiefer** [comment]
PR opened: https://github.com/yapplabs/ember-modal-dialog/pull/276

**Comment by lukemelia** [comment]
@benkiefer Thanks for your work on this and I apologize for not giving you a timely review and response. Are we covered by the just merged #277?

**Comment by benkiefer** [comment]
Yes, in the sense that the deprecation warnings are now silenced; however, everywhere the project is setting `destinationElementId` directly (from above example) needs to be changed to not do that anymore. Based on the deprecation warning, I think you've got until ember 4.0. Because the deprecation warnings are silenced, the modals may just stop working at some point and folks may not understand why.

**Comment by benkiefer** [comment]
Just checking in to make sure my response was clear. If there is anything I can do to help, let me know.
