### ISSUE TITLE
Ready to publish v3.0.0?

### ISSUE THREAD

**Issue by danwenzel** [yapplabs/ember-modal-dialog#280]
Version 3.0.0 is published to npm, but not listed in either the Releases tab or `CHANGELOG.md`

**Comment by danwenzel** [comment]
Hi @lukemelia - Any thoughts on this?

**Comment by lukemelia** [comment]
I just published 3.0.0-beta.4. If I can get some community confirmation that this version works well for people, we can make it 3.0.1 and yank 3.0.0.

**Comment by lukemelia** [comment]
Actually, I just ran `npm deprecate` on 3.0.0, so people will get a warning if they try to install it.

**Comment by BryanCrotaz** [comment]
It's been a year - can 3.0.0 be released yet?

**Comment by lukemelia** [comment]
3.0.1 has now been released. Thanks for the prompt @BryanCrotaz!
