### ISSUE TITLE
crossdomain.xml and robots.txt

### ISSUE THREAD

**Issue by sandstrom** [yapplabs/ember-modal-dialog#29]
This plugin seems to spawn `crossdomain.xml` and `robots.txt` in a folder named `ember-modal-dialog`, inside `dist`.

Is it possible to have them removed? [not spawned]

**Comment by lukemelia** [comment]
@sandstrom Yes. If you have a minute, you can PR the removal of those files from `public/`and I'll merge.

**Comment by sandstrom** [comment]
@lukemelia ah, that easy. PR in the mail! :mailbox:

**Comment by lukemelia** [comment]
Fixed by #30
