### ISSUE TITLE
error get onClose

### ISSUE THREAD

**Issue by wallacyalva** [yapplabs/ember-modal-dialog#297]
![image](https://user-images.githubusercontent.com/38988660/73941085-60ee1c80-48cb-11ea-9bae-dfcbb540135c.png)

when pressing to exit a modal returns me this error

version: v3.0.0-beta.3

**Comment by LucasSys** [comment]
Same here.

**Comment by lukemelia** [comment]
Make sure you are passing in a closure action instead of a string to `onClose`
