### ISSUE TITLE
Make composable with liquid-fire

### ISSUE THREAD

**Issue by ef4** [yapplabs/ember-modal-dialog#3]
[liquid-fire](http://github.com/ef4/liquid-fire) has its own modals API, but I'd like to take that out in favor of something like this addon, since "how to do modals" is really a separate concern from animation. Instead, it would be great if people could just use the liquid-fire animation helpers with ember-modal-dialog if they want to make their modals animate in & out.

Conceptually, to make this happen we would need to expose both 
- the active modal state
- and the ability to render it into DOM

into user's templates. For example, the default implementation of the top-level container could look like this in `application.hbs`:

``` handlebars
{{#with-active-modal as |modal|}}
  {{show-modal modal}}
{{/with-active-modal}}
```

(`with-active-modal` and `show-modal` would be components that are part of ember-modal-dialog. Better name suggestions welcome.)

Inserting the above snippet under the application root can still be done automatically for users who don't care about customizing. But users who do care can override by doing it themselves like this:

``` handlebars
{{#with-active-modal as |modal|}}
  {{#liquid-with modal as |modalVersion|}}
    {{show-modal modalVersion}}
  {{/liquid-with}}
{{/with-active-modal}}
```

(The above can actually get packaged up as a `{{liquid-modal-target}}` component in liquid-fire, so users aren't typing it. But the point is that `with-active-modal` and `show-modal` would become an extensible API offered by ember-modal-dialog.)

`liquid-with` controls versioning of the modal as it changes, and lets the liquid-fire transition rules govern how it will animate. Two common examples would be:
- when a modal is dismissed, the `modal` variable goes to undefined. But if `liquid-with` finds a matching animation rule, it will still render with the old `modalVersion` until that modal has a chance to animate away.
- if you switch directly from modal A to modal B, `liquid-with` can actually render its block twice, so that both modals can be on screen simultaneously, displaying a graceful transition between them.

If people like this idea I can work on it.

**Comment by lukemelia** [comment]
@ef4 I think the goal sounds great, and we would welcome your involvement!

I'm not sure if I've fully digested your concept, so a few questions/thoughts:

When you mention "active modal state", is that the template that a user is providing as the block to the modal-dialog helper?

The library currently does not limit the user to a single modal being visible at a time. Perhaps sensible UX does, but there's nothing in the current implementation that does. It sounds like in your proposed API, that restriction would be necessary.

Currently this addon supports routing to a modal. e.g. given a route `bar` nested under `foo`, and the template `foo/bar.hbs`:

```hbs
{{#modal-dialog}}
  Oh hai
{{/modal-dialog}}
```

... when you route to `/foo/bar` the "Oh hai" modal appears atop the `foo` template. If you transition away to say the `foo.index` route, the modal disappears.

The reason I bring up this case is because it was the driver to target a div _outside_ `application.hbs`. We originally tried to include the target div within the `application` template, but when we did, if a user routed directly to the modal route, we had a failure because the div was not yet present in the DOM [when the render is called and tries to access it](https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/components/overlay.js#L30).

It seems like we would need to figure out another approach to this in order to accommodate your suggested API.

**Comment by ef4** [comment]
> When you mention "active modal state", is that the template that a user is providing as the block to the modal-dialog helper?

Yes, the template and also the template's context. 

> The library currently does not limit the user to a single modal being visible at a time. Perhaps sensible UX does, but there's nothing in the current implementation that does. It sounds like in your proposed API, that restriction would be necessary.

I was picturing one at a time, but we could probably still support many at a time. Something like this as the default implementation would still give enough room to insert animation helpers:

```handlebars
{{#with-active-modals as |modals|}}
  {{#each modals as |modal|}}
    {{show-modal modal}}
  {{/each}}
{{/with-active-modals}}
```

Although to keep the animation rules from being really complex, I would probably just implement the animated version like this, so that it enforces one-at-a-time for people who opt into animations:

```handlebars
{{#with-active-modals as |modals|}}
  {{#liquid-with modals.lastObject as |modalVersion|}}
    {{show-modal modalVersion}}
  {{/liquid-with}}
{{/with-active-modal}}
```

> Currently this addon supports routing to a modal.

Yes, that's a very important case, without it you can't bind modal state into the URL correctly.

I think there may be a more Ember-ish way to handle this dependency: create a Service that all of these components use to talk to each other. When the `with-active-modals` component renders it registers itself with the service. When each `modal-dialog` renders it tells the service that it has a modal waiting. No matter what order those happen in, the service waits until it has both sides, and then tells the `modal-dialog "here's a morph, render into it now".

There may actually be an even simpler API, if I can make the animation helpers work from the "other side". That is, instead of wrapping them around the place where the modal is output high in the DOM, wrap them around the place where the modal appears in the template:

```handlebars
{{#liquid-if showingModal}}
  {{#modal-dialog}}Hello{{/modal-dialog}}
{{/liquid-if}}
```
If I can make that work, we may not need significant changes to ember-modal-dialog at all.

**Comment by lukemelia** [comment]
That last idea would be amazing, and would be very much in keeping with the elegance of our current usage pattern.

**Comment by krisselden** [comment]
@ef4 and @lukemelia this should already be compatible with liquid-fire, you just need to move the if.

```js
{{#modal-dialog}}
{{#liquid-if showingModal}}Hello{{/liquid-if}}
{{/modal-dialog}}
```

@ef4 question, can 'liquid-if' pause a liquid-outlet ancestor and make it wait for it to animate out?

**Comment by lukemelia** [comment]
@krisselden There is DOM generated by modal-dialog besides what is yielded. I think what you're saying is true if it was just

```
{{#ember-wormhole}}
  {{#liquid-if showingModal}}
    <div class="modal">etc</div>
  {{/liquid-if}}
{{/ember-wormhole}}
```

**Comment by krisselden** [comment]
`{{#ember-wormhole}} {{/ember-wormhole}}` would be a better name for it, it really isn't specific to modals, really just anything you want to show on top of the app

**Comment by krisselden** [comment]
lol, I was just commenting about your new name luke

**Comment by krisselden** [comment]
@lukemelia your example is correct, in fact the library and liquid fire could be combined to make a real modal-dialog

**Comment by lukemelia** [comment]
@krisselden we could extract `ember-wormhole` from this as it's own component, or addon, but `modal-dialog` provides additional functionality including a click-catching overlay behind the modal and positioning the modal relative to another element

**Comment by krisselden** [comment]
layout for the modal-dialog:

```
{{#ember-wormhole}}
  {{#liquid-if showingModal}}
    <div class="ember-modal-dialog">{{yield}}</div>
  {{/liquid-if}}
{{/ember-wormhole}}
```

**Comment by lukemelia** [comment]
@krisselden let's discuss. I think you are on to something but are ignoring functionality that this addon currently offers.

**Comment by stefanpenner** [comment]
Love the name wormhole

**Comment by lukemelia** [comment]
FYI, I am working on extracting an `ember-wormhole` addon from this project. It will become a dependency of this project that can also be used on it's own.

**Comment by ef4** [comment]
Glad to hear it, I was just looking at doing something similar.

**Comment by lukemelia** [comment]
I should have something up tonight.

**Comment by lukemelia** [comment]
https://github.com/yapplabs/ember-wormhole is released

**Comment by knownasilya** [comment]
Has there been any work on this? What's the recommended way to integrate with lf?

**Comment by bartocc** [comment]
+1 to have an update on this issue as well

**Comment by lukemelia** [comment]
Sorry, no progress on this as yet, folks. This is something we would like to support put not a priority for our own use cases. We're open to someone exploring possibilities for how this would be work and reporting back and/or PR if necessary.

**Comment by lukemelia** [comment]
FYI, @ef4 and I had a good discussion about this at Wicked Good Ember. We think it is possible by providing the ability for ember-wormhole (which this library is built on top of) to target a "liquid-wormhole" and implementing this concept in liquid-fire. No immediate timeline, I'm afraid, but that is the general plan.

**Comment by Padchi** [comment]
Status on the "liquid-wormhole"?

**Comment by knownasilya** [comment]
Would also love to see this, otherwise the UI is too jarring and makes the app feel sloppy.

**Comment by lukemelia** [comment]
@Padchi I haven't tried it yet, but @pzuraq created http://pzuraq.github.io/liquid-tether

**Comment by knownasilya** [comment]
@lukemelia thanks for reminding me. I saw it before but forgot that it existed. So many good addons to keep track of..

**Comment by jreading** [comment]
Super need a `liquid-wormhole` right now. Anyone have any workarounds in the meantime?

**Comment by pzuraq** [comment]
@jreading check out the [liquid-wormhole](http://pzuraq.github.io/liquid-tether/#/examples?a=liquid-wormhole) part of liquid-tether.

Note that it doesn't work exactly the same way as ember-wormhole. It solves the case of warping an element above the DOM, where you can easily use it to animate a modal or such, but is not as general.

**Comment by ofridagan** [comment]
+1

**Comment by brandensilva** [comment]
:+1:

**Comment by mirague** [comment]
Any news on best practices of adding animations to dialogs?

**Comment by ef4** [comment]
There is a complete animated modal example in https://github.com/ef4/ember-elsewhere/

If somebody wants to work on replacing switching this addon from ember-wormhole to ember-elsewhere, it will become fully animatable by liquid-fire.

**Comment by lukemelia** [comment]
This library supports animation via liquid-fire as of [2.2.0](https://github.com/yapplabs/ember-modal-dialog/releases/tag/v2.2.0)

**Comment by jacobq** [comment]
Does anyone have a live demo/example showing how to use ember-modal-dialog with liquid-fire? I'm trying to make the modal portion "slide in" using the following:

```
    this.transition(
        this.hasClass('ember-modal-dialog'),
        this.toValue(true),
        this.use('toUp', {duration: 600, easing: 'easeInOutQuad'}),
        this.reverse('toDown', {duration: 600, easing: 'easeInOutQuad'}),
        this.debug()
    );
```

But the rule doesn't match: `[liquid-fire] Checking transition rules for <div id=​"ember951" class=​"liquid-container ember-view">...rejected because parentElementClass was liquid-container ember-view liquid-animating...`. If I try using `this.childOf('ember-modal-overlay'),` I have a similar problem. If I try to use `this.hasClass('ember-modal-wrapper'),` the rule matches, but it matches the background overlay as well (which I want to fade in while sliding in the "window" portion).

Any help is appreciated.

**Comment by knownasilya** [comment]
I have a similar setup (although not for emd) that might help https://github.com/knownasilya/bootstrap-modal/blob/master/addon/utils/default-transition.js

**Comment by jacobq** [comment]
Thanks @knownasilya I didn't know about `explode` and that seems to be the crux of my problem. Based on your example I now have something like this, which seems to work:

```
    const fadeOptions = {duration: 100, easing: 'easeInOutQuad'};
    const modalOptions = {duration: 600, easing: 'easeInOutQuad'};

// ...
// Modal dialogs
    this.transition(
        this.toValue(true),
        this.use('explode', {
            pick: '.ember-modal-dialog',
            use: ['toUp', modalOptions]
        }, {
            pick: '.ember-modal-overlay',
            use: ['crossFade', fadeOptions]
        }),
        this.reverse('explode', {
            pick: '.ember-modal-dialog',
            use: ['toDown', modalOptions]
        }, {
            pick: '.ember-modal-overlay',
            use: ['crossFade', fadeOptions]
        }),
        //this.debug()
    );
```

**Comment by jlami** [comment]
I could only get the reverse to work by using `this.toValue(0)`. The code in the dummy app also doesn't seem to work. `this.toValue((toValue, fromValue) => toValue === null || fromValue === null)`
Anybody have an idea why this is?

I am using the following versions:
    "ember-modal-dialog": "^2.3.0",
    "liquid-fire": "^0.27.3",
    "liquid-wormhole": "^2.0.7",
