### ISSUE TITLE
Deprecation warnings with Ember 3.26+

### ISSUE THREAD

**Issue by pgengler** [yapplabs/ember-modal-dialog#319]
Beginning with Ember 3.26, [implicit injections are deprecated](https://deprecations.emberjs.com/v3.x#toc_implicit-injections), leading to deprecation warnings like this:
> `A value was injected implicitly on the 'destinationElementId' property of an instance of <app-name@service:modal-dialog::ember616>, overwriting the original value which was null. Implicit injection is now deprecated, please add an explicit injection for this value. If the injected value is a service, consider using the @service decorator.`

Additionally, [`this.`-fallback in templates is deprecated](https://deprecations.emberjs.com/v3.x/#toc_this-property-fallback):
> The `modalDialogComponentName` property path was used in a template for the `ember-modal-dialog/templates/components/modal-dialog.hbs` component without using `this`. This fallback behavior has been deprecated, all properties must be looked up on `this` when used in the template: {{this.modalDialogComponentName}}

(Similarly for `attachment`, `attachmentClass`, `clickOutsideToClose`, `constraints`, `containerClass`, `containerClassNames`, `destinationElementId`, `hasOverlay`, `offset`, `overlayClass`, `overlayClassNames`, `overlayPosition`, `stack`, `target`, `targetAttachment`, `targetAttachmentClass`, `targetModifier`, `targetOffset`, `tetherClassPrefix`, `tetherTarget`, `translucentOverlay`, `value`, `wrapperClass`, `wrapperClassNames`, etc.)

This is happening with the latest release of ember-modal-dialog (3.0.2).

**Comment by alexlafroscia** [comment]
It seems like this should be fixed on master; @lukemelia is it possible to cut a release that includes those fixes?

**Comment by bartocc** [comment]
Hi 👋 any news on a possible 3.0.4 release?

**Comment by lukemelia** [comment]
@bartocc can you try 4.0.0-alpha.1 and see if fixes this issue for you? If so, I can promote it to a 4.0.0 release.

**Comment by bartocc** [comment]
`4.0.0-alpha.1` works for us @lukemelia 👍

**Comment by lukemelia** [comment]
Closing as resolved. 4.0.0-beta.0 is out and we'll hopefully have 4.0.0 stable this week.
