### ISSUE TITLE
Issue with ember 3.27

### ISSUE THREAD

**Issue by romgere** [yapplabs/ember-modal-dialog#320]
Hey 👋🏻 When I'm using `ember-modal-dialog` with last ember release (`3.27.0`) I have the following error : 

`index.js:460 Uncaught TypeError: Cannot create property 'Symbol(INIT_FACTORY)' on string 'my-modal-dialog-destination'`

After some investigations it seems related to the way the id of modal destination is injected into `modal-dialog` service.

The error is throw here : https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/components/modal-dialog.js#L22

I'm not expert in how ember injection works, but it seems the `{ instantiate: false }` option from here is ignored : 

https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/initializers/add-modals-container.js#L40-L44

I tested on ember 3.26.1 & don't reproduce...

I had a look to 3.27.0 release note & don't see any changes related to this 🤔

**Comment by lukemelia** [comment]
@romgere Thanks for the bug report. Sounds like something we should fix, but also sounds like a bug in Ember 3.27 that should be reported if it broke backward compatibility.

**Comment by romgere** [comment]
@lukemelia First, thx for the fast answer 🙏🏻 Second, I also think about an issue on ember side, but not totally sure... I asked on discord & currently trying to reproduce the issue on a fresh app before opening any issue on ember side.

**Comment by lukemelia** [comment]
Sounds good. The Ember core team is generally quite keen to know if they accidentally broke backward compatibility.

**Comment by romgere** [comment]
I'm able to reproduce on fresh app (issue happens when updating from ember-source 3.26.1 to 3.27.0)...
I opened the issue on ember side : https://github.com/emberjs/ember.js/issues/19532

**Comment by lukemelia** [comment]
Well articulated, thanks @romgere!

**Comment by lukemelia** [comment]
Workaround released in v3.0.3
