### ISSUE TITLE
Release of 4.0.0?

### ISSUE THREAD

**Issue by rahulk94** [yapplabs/ember-modal-dialog#363]
Hey there, quick question around the timing of when 4.0.0 will be released?

I'm currently upgrading our EmberJS application to 3.28 and noticed the 3.x releases still use `ember-cli-babel@6` which results in some deprecation warnings. These have been fixed on the `4.0.0-alpha` stream so basically wondering when this will be ready enough for an official release.

Fwiw I've noticed there are currently failing builds for the Embroider safe and optimized builds so happy if the plan is to fix those up before doing a official 4.0 release.

**Comment by rahulk94** [comment]
This will be done after Ember@4 and Embroider compatibility per https://github.com/yapplabs/ember-modal-dialog/issues/309#issuecomment-889667365

**Comment by lukemelia** [comment]
4.0.0-beta.0 is now out.

**Comment by lukemelia** [comment]
4.0.0 has been released!
