### ISSUE TITLE
does not work with engines (release 4.0.0-alpha.1)

### ISSUE THREAD

**Issue by IgorKvasn** [yapplabs/ember-modal-dialog#364]
Current alpha version (4.0.0-alpha.1) does not seem to work in engines - I am experiencing the same bug as described here #233 that was already fixed in #315.

It looks like there was a bad git merge or something, because the fix in #315 is not present in the master branch, namely file _addon/initializers/add-modals-container.js_ is missing in the master

When I revert my package.json to use ember-modal-dialog 3.0.3, engines are working fine again

**Comment by lukemelia** [comment]
@IgorKvasn thanks for this report. Please try the branch in #372 and let me know if it works in your app. I would love to add test coverage so that we don't regress on this again. I don't use engines or know much about testing compatibility though, so any help is welcome.

**Comment by IgorKvasn** [comment]
I tried the branch #372 and it does not seem to work :( I am getting error 
```
  Uncaught Error: Assertion Failed: Could not find the root Application for '<(unknown):ember227>'.
    at assert (index.js:181:1)
    at Object._default [as initialize] (add-modals-container.js:39:1)
    at index.js:140:1
    at Vertices.each (dag-map.js:231:1)
    at Vertices.walk (dag-map.js:145:1)
    at DAG.each (dag-map.js:75:1)
    at DAG.topsort (dag-map.js:83:1)
    at Class._runInitializer (index.js:155:1)
    at Class.runInstanceInitializers (index.js:138:1)
    at Class._bootSync (instance.js:111:1)
```
I did a little bit of debugging and it seems that this "if" condition does not pass https://github.com/yapplabs/ember-modal-dialog/blob/d52eb314517d2e809772e144cbc998f58afc43c8/addon/instance-initializers/add-modals-container.js#L31

I can see in the debugger, that `instance` is in fact instance of Application, but instanceof does not seem to pass - I am sorry, I don't know how to fix it :(

**Comment by Windvis** [comment]
I think that check fails because it's an [`ApplicationInstance`](https://api.emberjs.com/ember/release/classes/ApplicationInstance) instead of an `Application`? In #315 it was still a normal initializer.

Other than that I have no input since I haven't worked with Engines yet either :smile:.

**Comment by lukemelia** [comment]
@IgorKvasn I've adjusted #372. Please give it another try.

**Comment by IgorKvasn** [comment]
thanks a lot - it works with (lazy) engines as well as normal Application

**Comment by lukemelia** [comment]
Thanks, merged. This will be in 4.0.0-beta.1
