### ISSUE TITLE
Needs live demo

### ISSUE THREAD

**Issue by brian-gates** [yapplabs/ember-modal-dialog#37]
Live demo please :)

**Comment by chrislopresto** [comment]
@brian-gates There are a bunch of live demos in the included dummy app. The README explains everything. Let us know if you have any problems getting things running.

https://github.com/yapplabs/ember-modal-dialog#ember-modal-dialog

> Test examples are located in tests/dummy/app/templates/application.hbs and can be run locally by following the instructions in the "Installation" and "Running" sections below.

**Comment by brian-gates** [comment]
Those aren't "live". I meant something someone can click and see.  Not everyone has a dev environment when they want to see how this thing works.

**Comment by chrislopresto** [comment]
Gotcha. Reopening.

**Comment by chrislopresto** [comment]
Here you go: http://yapplabs.github.io/ember-modal-dialog/

Updated the README accordingly. Thanks for the nudge.

**Comment by brian-gates** [comment]
Awesome! :+1:
