### ISSUE TITLE
Ember 3.28: TypeError: this.containerClassNames.join is not a function

### ISSUE THREAD

**Issue by danielxdam** [yapplabs/ember-modal-dialog#377]
In Ember 3.28 with ember-modal-dialog 4.0.0 we are getting an error when opening the dialog:

`Uncaught (in promise) TypeError: this.containerClassNames.join is not a function     basic-dialog.js:37`

It looks like basic-dialog.js at line 43 is expecting `this.containerClassNames` to be an array or null but instead it is a string of the css class names passed in `@containerClassNames`.

We are extending the `ModalDialog` class but we haven't made any changes to the `@containerClassNames` in our subclass. That argument is just being passed on to the parent.

This may be related to or a duplicate of: #374 .

**Comment by lukemelia** [comment]
I believe this is fixed.
