### ISSUE TITLE
Deprecated in ember-cli 0.2.6

### ISSUE THREAD

**Issue by kirley** [yapplabs/ember-modal-dialog#39]
I just installed ember-cli 0.2.6 and it threw me a deprecated waring:
```
[Deprecated] this.pickFiles is deprecated, please use broccoli-funnel directly instead  [addon: ember-modal-dialog]
```

**Comment by stefanpenner** [comment]
@kirley do you have na older version? pickFiles does not exist in this project.

**Comment by kirley** [comment]
Okay cool, ember-modal-dialog is used as a dependent object in another ember addon.  I’ll make an issue to have them update to the latest version of your addon.

**Comment by sgasser** [comment]
Really strange... 
I get the same error, but in the the entire folder pickFiles only used in one file of ember-cli: node_modules/ember-cli/lib/models/addon.js

**Comment by stefanpenner** [comment]
this is a bug in ember-cli: should be fixed by -> https://github.com/ember-cli/ember-cli/pull/4206

**Comment by stefanpenner** [comment]
ember-cli@v0.2.7 is out, it should address this issue.

**Comment by sgasser** [comment]
Yes fixed. Thanks @stefanpenner

**Comment by stefanpenner** [comment]
:+1:
