### ISSUE TITLE
Access to `navigator` in module scope crashes Fastboot

### ISSUE THREAD

**Issue by gilest** [yapplabs/ember-modal-dialog#399]
Regression introduced in `4.1.3`. Rendering a modal in a Fastboot application will crash the server:

```
const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent);
                                      ^
ReferenceError: navigator is not defined
```

Code here:
https://github.com/yapplabs/ember-modal-dialog/commit/65a84d58a99c75540d77cef21d59f578fa3d0f19#diff-e6e71d63dfb8f6989d87cbf93a6109a03917d85d083f2c11044875be495753deR14

Fix may be as simple as allowing for the fact that `navigator` may be `undefined`.

**Comment by lukemelia** [comment]
Thanks, @gilest. I'm leaving for a trip shortly and may not get to deal with this. If anyone wants to submit a PR, that woulds be great. Sounds like we also need a fastboot test suite to run in CI.
