### ISSUE TITLE
Extending modal-dialog subclass doesn't work

### ISSUE THREAD

**Issue by dmagunov** [yapplabs/ember-modal-dialog#40]
Ember 1.12.1

When extending modal-dialog component, there are no modal displayed, just inline html appended to the body

SomeModalDialogComponent = ModalDialog.extend()

**Comment by lukemelia** [comment]
@dmagunov I updated the `master` branch to ember 1.12.1 and deployed the result to our demo page: http://yapplabs.github.io/ember-modal-dialog/ As you can see, there is an working example of using a custom subclass.

Take a look at the "dummy" app in the source code and see if you can tell what you're doing something differently.

**Comment by dmagunov** [comment]
Hello,

I've use Your example from readme.md

application.hbs

```handlebars
{{#aww-modal-dialog close="toggleModal"  alignment="center"  translucentOverlay=true}}
    Oh hai there!
{{/aww-modal-dialog}}
```

```coffeescript
`import Ember from 'ember'`
`import ModalDialog from 'ember-modal-dialog/components/modal-dialog'`

AwwModalDialogComponent = ModalDialog.extend

	setup:(->
		Ember.$('body').on 'keyup.modal-dialog', (e) => 
			
			if e.keyCode == 27
				@sendAction('close')

	).on('didInsertElement')

	teardown: (->
		Ember.$('body').off('keyup.modal-dialog')
	).on('willDestroyElement')
	
`export default AwwModalDialogComponent`
```

screenshot
![screen shot 2015-06-08 at 2 11 14 pm 3](https://cloud.githubusercontent.com/assets/3579475/8033585/6fb60e08-0de8-11e5-8382-102c45864f77.png)

Ember 1.12.1
Ember Data 1.0.0-beta.19

If I use modal-dialog component - all working good.

**Comment by lukemelia** [comment]
@dmagunov you would need to inject the destinationElementId into your subclass. The subclass example in the dummy app does this here: https://github.com/yapplabs/ember-modal-dialog/blob/master/tests/dummy/app/initializers/register-subclassed-modals.js
