### ISSUE TITLE
Missing dependency on @ember/string

### ISSUE THREAD

**Issue by bjornharrtell** [yapplabs/ember-modal-dialog#402]
I suspect this is cause of sudden "Could not find module @ember/string imported from ember-modal-dialog/components/modal-dialog", after a transitive dependency upgrade. As of yet unable to find out which transitive dep is causing the break.. but nevertheless, I think it's an error that ember-modal-dialog doesn't declare that it has dependency on `@ember/string`. Similar problem as https://github.com/emberjs/ember-inflector/pull/501.

**Comment by bjornharrtell** [comment]
I found that the break occurs when upgrading `@ember/string` from 3.0.0 to 4.0.0.

**Comment by lukemelia** [comment]
Addressed in #403
