### ISSUE TITLE
Sass mandatory?

### ISSUE THREAD

**Issue by Dfmarulanda** [yapplabs/ember-modal-dialog#42]
is sass mandatory for the use of this library?. If not, i think the README is not clear.
If yes, the README should be more clear.
TY.

**Comment by lukemelia** [comment]
Hi @Dfmarulanda. We provide an scss implementation of required styles, but if you're not using sass, you can define similar css in your app. This is a frequently customized portion, and shipping static css in vendor.css that you can't get rid of didn't seem appropriate.

Would you like to take a crack at improving the README to be clearer about this?

**Comment by Dfmarulanda** [comment]
Im working in with it but, it was kind of suggestion.
