### ISSUE TITLE
Pass-thru tether args

### ISSUE THREAD

**Issue by johnnyshields** [yapplabs/ember-modal-dialog#46]
Currently it looks like there's a number of tether args such as `contraints` which are not exposed to the embedded ember-tether component. It would be useful to enable passing-thru these args.

**Comment by chrislopresto** [comment]
Agreed. I also want to clean up the existing set of modal dialog properties now that tether is in the mix.

**Comment by johnnyshields** [comment]
Any movement on this issue?

**Comment by chrislopresto** [comment]
No movement on this yet. We'll gladly accept help, as it would be nice functionality to wire up.

**Comment by lukemelia** [comment]
`constraints` has been added. I don't want to enable passthrough args because I want to reserve the ability to swap out ember-tether in the future if appropriate.
