### ISSUE TITLE
Leverage a dedicated library for positioning

### ISSUE THREAD

**Issue by lukemelia** [yapplabs/ember-modal-dialog#5]
Perhaps https://github.com/HubSpot/tether

**Comment by stefanpenner** [comment]
cool lib:

thing it doesn't appear do, and will likely need to be added

* clientBoundingRect based removal (for list view);

It also isn't clear that we can auto-detect the list-view container. A previous approach was using clientBoundingRect and rAF, which yes does poll quite often but was able to handle the list-view case nicely.

I am not recommending not using this library, just that further work will likely be needed.

**Comment by taras** [comment]
I used this library for modal component that I created for one of the previous projects and worked very well. I believe Freshbooks might have also used it to implement tooltips & possibly modals.

**Comment by lukemelia** [comment]
Well, hey, we did it in 0.7.0! Huzzah!

**Comment by chrislopresto** [comment]
:clap: :fireworks:
