### ISSUE TITLE
modal-dialog template disjunction in >0.7.3 breaks dependency setup

### ISSUE THREAD

**Issue by LexLythius** [yapplabs/ember-modal-dialog#52]
````
Uncaught Error: Could not find module `ember-modal-dialog/templates/components/modal-dialog` imported from `ember-modal-dialog/components/modal-dialog`
````
Obviously the problem is we now have two separate subdirs to get an Ember version-specific template from, and the workaround is to move/copy the appropriate .hbs file to parent directory. However, from the install-dependencies-and-run standpoint, this breaks the build.

**Comment by lukemelia** [comment]
@LexLythius the build is passing on Travis and we're using the latest ember-modal-dialog in our own apps. Can you be more specific about your configuration and issue?

**Comment by toovy** [comment]
@lukemelia I'm having the same issue with the latest build, when installing 0.7.2 it works. I'm using Ember 1.13.3 and ember-cli 1.13.1, also I've not installed the addon directly, but either it is used by materialize (http://mike.works/ember-cli-materialize/#/modal). The issue occurs when I try to use the md-modal component in any .hbs. Hope this helps to locate the issue.
BR, toovy

**Comment by lukemelia** [comment]
I was able to reproduce this problem using an old version of ember-cli, but upgrading ember-cli to 1.13.1 fixed the problem.

**Comment by toovy** [comment]
@lukemelia thanks! I can confirm that 0.7.5 needs ember-cli 1.13.1. Now works fine.
