### ISSUE TITLE
Hide on click out with hasOverlay=false

### ISSUE THREAD

**Issue by kellyselden** [yapplabs/ember-modal-dialog#55]
The use case is a modal that is off to the side, not inhibiting your use of the page. You can still get hover effects and link cursor changes, but your first click hides the modal. I have accomplished this with:
```js
const teamMembersClickEvent = 'click.team-members';
//...
  didInsertElement() {
    this.set('clickOutElement', Ember.$('#modal-overlays + .ember-view'));
  },

  toggleTeamMembers() {
    var clickOutElement = this.get('clickOutElement');
    if (this.toggleProperty('shouldShowTeam')) {
      clickOutElement.on(teamMembersClickEvent, () => this.send('toggleTeamMembers'));
    } else {
      clickOutElement.off(teamMembersClickEvent);
    }
  },

  actions: {
    toggleTeamMembers() {
      // debounce because click event and action can both trigger at once
      Ember.run.debounce(this, this.toggleTeamMembers, 0);
    }
  }
```
Is this something you would want to add, or leave it up to the consumer?

**Comment by lukemelia** [comment]
Why not just make the overlay transparent in this case?

**Comment by kellyselden** [comment]
If the user wanted to manipulate the page, or click a link, it would take two clicks instead of one.

**Comment by lukemelia** [comment]
Ah, I see. If there is a nice way to add opt-in support for this, I'm open to a PR!

**Comment by kellyselden** [comment]
Added in #59.
