### ISSUE TITLE
ember-modal-dialog doesn't work with IE8

### ISSUE THREAD

**Issue by benkonrath** [yapplabs/ember-modal-dialog#57]
Thanks for making this library. It's been working well for me during my development but it's not working on Win 7 / IE8 which is unfortunately a requirement for the project I'm currently working on.

When I try to load the [demo page](http://yapplabs.github.io/ember-modal-dialog/) with IE8, I get a blank page with this error message in the console:
```
Object doesn't support this property or method
```
The error directs me to this line of the compiled app:
```
Ember.keys(requirejs._eak_seen).map(function(e){return{moduleName:e,matches:r.exec(e)}}).filter( <snip>
```

When I try to load my application that uses ember-modal-dialog (in dev mode) with IE8, I get a blank app with these console messages:
```
DEPRECATION: Ember.keys is deprecated in favor of Object.keys
Expected identifier
DEPRECATION: Ember.keys is deprecated in favor of Object.keys
Expected identifier
```
The `Expected identifier` error directs me to the `exports.default =` line of this block:
```
define('content-app/components/ember-wormhole', ['exports', 'ember-wormhole/components/ember-wormhole'], function (exports, ember_wormhole) {
    'use strict';
    exports.default = ember_wormhole.default;
});
```
I'm using these versions of Ember and related libraries in my application:
```
DEBUG: Ember      : 1.13.3
DEBUG: Ember Data : 1.13.5
DEBUG: jQuery     : 1.11.3
```

I'm curious to know if supporting IE8 is something that you are interested in doing (if it's even possible). Obviously this would only be for a version that's compatible with Ember 1.13 as IE8 will go away in Ember 2.0. For me it's ok if the solution is that I need to add a polyfill for some functionality that's missing in IE8. If this is the way to go, could you point me in the right direction for which polyfills I'd need to use? Thanks.

**Comment by benkonrath** [comment]
Just a quick update: I was able to get ember-modal-dialog working on IE8 with a production build. The `exports.default =` line in ember-wormhole seems to be tripping up IE8 while serving the files in dev mode as mentioned above.

```
exports.default = ember_wormhole.default;
```
I don't know enough about ES6 modules to know what's going on. I did notice that other modules use `exports['defaults']` but I'm not sure if this is the cause of the problem. Should I file an issue with ember-wormhole about this?

The demo page for ember-modal-dialog not working in IE8 is probably related to using some newer JS feature the IE8 doesn't know about. It doesn't seem to be an issue directly with ember-modal-dialog or ember-wormhole.

**Comment by benkonrath** [comment]
I found the issue with ember-wormhole. I'll leave this open so you can decide if you want the demo page to work on IE8. Feel free to close this issue if it's not something you're planning to fix.

**Comment by stefanpenner** [comment]
issue in the module transpiler, this should fix it: (when it lands) https://github.com/esperantojs/esperanto/pull/176

**Comment by benkonrath** [comment]
Thanks for pointing me in right direction.
