### ISSUE TITLE
Doesn't respect deferReadiness, advanceReadiness

### ISSUE THREAD

**Issue by gouthamvel** [yapplabs/ember-modal-dialog#64]
My ember application in initialized in certain pages only so I use deferReadiness to halt ember app if required. ember-modal-dialog throws up a error when no ember root-element is found

``` javascript
   // The initializer I use to check for ember root-element
   var Initializer = {

     name: 'check-root-element',

     initialize: function(container, app) {
       app.deferReadiness();
       jQuery(function() {
         if ( jQuery( "#admin-ember-app" ).length ) {
           app.advanceReadiness();
         }
       });
     }

   };

   export default Initializer;
```

Here's the error from console 

> Uncaught TypeError: Cannot read property 'appendChild' of null
> appendContainerElement @ add-modals-container.js:17
> exports.default @ add-modals-container.js:33

Any idea how I can solve this?

**Comment by lukemelia** [comment]
@gouthamvel I'm sure you've solved this two years later, but for others viewing this I would say you could override the initializer that ember-modal-dialog adds to have conditional logic, or adjust your own logic to not start booting the ember app in the first place if you don't want it booted. Apologies for not responding sooner to this.
