### ISSUE TITLE
Modal positioning fails after browser resizing

### ISSUE THREAD

**Issue by elidupuis** [yapplabs/ember-modal-dialog#68]
I have a modal with the following positioning (using Ember Tether):
```
alignmentTarget='body'
attachment='top right'
targetAttachment='top right'
```

This renders the modal, as expected, in the top right corner of the screen. However, as soon as I resize the browser, the modal jumps to the top left of the screen and stays there.

Thoughts?

**Comment by chrislopresto** [comment]
@elidupuis Do you have any errors in the console?

**Comment by elidupuis** [comment]
Nope. Console is clean.

**Comment by chrislopresto** [comment]
I am not able to reproduce. Can you post more context?

**Comment by elidupuis** [comment]
Hmmm. Just tried this again in a fresh project and I can't replicate it either :frowning: I'll see if I can figure out what else could be going on.

**Comment by elidupuis** [comment]
Looks like it was some stray CSS via a `body > .ember-view` selector that was conflicting with the Tether positioning styles. So not a bug at all :smiley: 

Sorry. Carry on.

**Comment by chrislopresto** [comment]
That could certainly wreak havoc. Cheers.
