### ISSUE TITLE
Custom modal template

### ISSUE THREAD

**Issue by patrickberkeley** [yapplabs/ember-modal-dialog#69]
Is it possible/expected to have content in a custom modal's corresponding template? For example from [the section on custom modals in the readme](https://github.com/yapplabs/ember-modal-dialog#custom-modals), this mean content in `app/templates/components/full-screen-modal.hbs` would render within the custom modal.

**Comment by patrickberkeley** [comment]
FWIW this was working a few versions of ember and ember-modal-dialog ago (not sure exactly where it stopped working), but does not work with ember-cli 1.13.1 and ember-modal-dialog 0.7.7.

**Comment by patrickberkeley** [comment]
Turns out I needed to specify a the template explicitly ([same as this addon does](https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/components/modal-dialog.js#L2-L19)):

```js
import ModalDialog from 'ember-modal-dialog/components/modal-dialog';
import template from '../templates/components/simple-menu';

export default ModalDialog.extend({
  layout: template
});
```

**Comment by joshuairl** [comment]
@patrickberkeley Does this still work?
It doesn't seem to work for me?

**Comment by joshuairl** [comment]
My bad, I think it's because I wasn't using Ember tether and I was putting it in the ember-tether area.

Ignore me.
