### ISSUE TITLE
Alignment 'none' issue in positioned container

### ISSUE THREAD

**Issue by mitchlloyd** [yapplabs/ember-modal-dialog#75]
After an upgrade I'm getting an error inside of positioned container:  https://github.com/yapplabs/ember-modal-dialog/blob/v0.7.7/addon/components/positioned-container.js#L56

I'm using the `renderInPlace: true` option when testing which sets alignment to the string 'none'. However there is no `alignNone` method for positioned-container. 

My current workaround is this:  

```javascript
import EmberModalDialogPositionedContainerComponent from 'ember-modal-dialog/components/positioned-container';
import Ember from 'ember';
const { computed } = Ember;

export default EmberModalDialogPositionedContainerComponent.extend({
  isPositioned: computed('alignment', 'alignmentTarget', function() {
    if (this.get('alignment') === 'none') {
      return false;
    }

    return this._super(...arguments);
  }),
});
```

I must say it is so great to be able to override these components, so thanks for that!

**Comment by chrislopresto** [comment]
@mitchlloyd Thanks for filing this. We have a fix on the branch that is the basis for the next release. We'll keep you posted.

**Comment by chrislopresto** [comment]
@mitchlloyd This is fixed in https://github.com/yapplabs/ember-modal-dialog/releases/tag/v0.8.0 Thanks!

**Comment by mitchlloyd** [comment]
@chrislopresto Thanks for following up!
