### ISSUE TITLE
About integration tests

### ISSUE THREAD

**Issue by gzurbach** [yapplabs/ember-modal-dialog#78]
Hey there!

I found a dead link in the README file, section **Unit Tests**: "See this [example](https://github.com/yapplabs/ember-modal-dialog/blob/master/tests/unit/components/component-that-uses-modal-dialog-test.js) for how to set this up in a unit test."

I found the deleted file by browsing older versions of this repo, but I was wondering whether there is a new (simpler?) way of writing an integration test for a component that subclasses (or contains) a `modal-dialog`.

My current issue concerns the `destinationElementId`. Since I am only rendering the component I'm testing, the destination element does not exist. Changing the value of `modalRootElementId` in `environment.js` does not seem to work either.

The [deleted test](https://github.com/yapplabs/ember-modal-dialog/blob/c91bd37fe2bcf0315b99dc1a06d4d49eb0eda8c8/tests/unit/components/component-that-uses-modal-dialog-test.js) suggested to `appendChild` on `#ember-testing`. Is it still the right thing to do?

Thanks!

**Comment by gzurbach** [comment]
Ok I just realized that we are not using `environment.js` in our project. I solved my problem by passing `destinationElementId` to my component during the test. Which gives (using mocha):
```javascript
describeComponent(
  'fancy-modal',
  'Integration: FancyModalComponent',
  {
    integration: true
  },
  function() {
    beforeEach(function() {
      // This should be configured in environment.js but we are not using this file at the moment
      this.set('destinationElementId', 'ember-testing');
    });
    it('works like a charm', function() {
      this.render(hbs`{{fancy-modal destinationElementId=destinationElementId}}`);
      expect($('.my-confirm-button')).to.have.length(1); // we can't use `this.$` here
    });
  }
);
```
Note that in any other integration test we would write `expect(this.$('.my-confirm-button'))...` but in our case it won't work because `this.$` refers to the rendered component only. So I had to remove it: `expect($('.my-confirm-button'))...`.

I'd be happy to send a small PR explaining how to write an integration test in the README. It might help other devs in the future?

**Comment by jrjohnson** [comment]
This solution isn't working for me with Ember 1.13.5 and qunit.  I'm guessing this.set doesn't reach the same scope.  My testing container seems to be called `ember-testing-container` but that also doesn't help.  Any advice on using this component in an integration test?

**Comment by gzurbach** [comment]
Yep sorry I should have updated my solution. This is what I'm doing now:

```javascript
it('renders', function() {
  let modalDialogService = this.container.lookup('service:modal-dialog');
  modalDialogService.destinationElementId = 'fancy-div';

  this.render(hbs`<div id='fancy-div'></div>{{fancy-modal}}`);
  expect(this.$()).to.have.length(1); // note that you can use this.$ again
});
```

**Comment by jrjohnson** [comment]
That work great!  Thanks.

**Comment by corrspt** [comment]
I faced the same problem today, thanks @gzurbach for the help.

I'm going to paste the error I got here in the hopes that google will index it and so when the next guy searches for it, hopefully it will bring him here :+1: 

```javascript
Error: ember-wormhole failed to render content because the destinationElementId was set to an undefined or falsy value.
```

**Comment by jondayton** [comment]
@gzurbach @corrspt thanks the google search worked.

**Comment by JackCA** [comment]
thanks everyone

**Comment by ForSpareParts** [comment]
If I understand correctly, this happens because the `destinationElementId` is, ultimately, determined by a property set on the modal service in an initializer -- which happens because we need to create wrapper element for modal overlays at runtime.

While this makes sense in real applications, it also seems like their should be some kind of defensive-coding compromise that provides useful behavior in a test context. I'm thinking either:

* Provide a fallback ID in the service that can be used if no injected ID is present. We could use environment config to set this to `#ember-testing`, for instance, in tests. In normal development/production contexts, it would remain undefined to preserve the real-app behavior.
* Default to rendering in-place if no injected ID is present (I know this is an acceptable behavior in my integration tests, but I'm not sure about everybody else's...)

@chrislopresto, @lukemelia: thoughts?

**Comment by lukemelia** [comment]
@ForSpareParts I'm open to exploring falling back to `#ember-testing` in test mode

**Comment by JackCA** [comment]
Have found myself here again 😃 

Should the dead link in the README that is mentioned in the original comment for the issue at least be removed?
