### ISSUE TITLE
Feature Request? Trigger Modal Resize

### ISSUE THREAD

**Issue by coladarci** [yapplabs/ember-modal-dialog#80]
Obsessed w/ this add-on and am interested if you have any suggestions on how to handle a common scenario we have where the modal content changes as you interact w/ it and we want to reposition the dialogue, either automatically (ideally) or somehow trigger it.

And suggestions on how to pull this off? I'm happy to put out a pull if you think it's reasonable!

**Comment by lukemelia** [comment]
@coladarci If you are using ember-tether with ember-modal-dialog and call `Tether.position()`, Tether will remeasure and reposition all of it's "tethers" including active ember-modal-dialogs. You could use `Ember.run.scheduleOnce` this to run on the `afterRender` run loop queue when one of your content properties change.
