### ISSUE TITLE
dependency on ember-cli-htmlbars@0.7.9 is too restrictive

### ISSUE THREAD

**Issue by spovich** [yapplabs/ember-modal-dialog#87]
`ember-cli-htmlbars` is currently at `1.0.1` but this is pinned at exactly `0.7.9`.  I upgraded to `1.0.1` and modals are good.  Can this dependency be loosened up to be `>= 0.7.9`?

**Comment by xtian** [comment]
+1

**Comment by chvonrohr** [comment]
:+1:

**Comment by ryanjm** [comment]
Working on upgrading my project and ran into this. Loosening the requirement would be helpful.

**Comment by lukemelia** [comment]
This was addressed a while back.
