### ISSUE TITLE
close on 'escape'

### ISSUE THREAD

**Issue by samselikoff** [yapplabs/ember-modal-dialog#9]
What's the suggested way to add close-on-escape functionality? I tried using `keyPress`

```js
import ModalDialog from 'ember-modal-dialog/components/modal-dialog';

export default ModalDialog.extend({

  keyPress() {
    console.log('pressed!');
  }
});
```

but it didn't work. Here's what I have now:

```js
import ModalDialog from 'ember-modal-dialog/components/modal-dialog';

export default ModalDialog.extend({

  setup: function() {
    Ember.$('body').on('keyup', (e) => {
      if (e.keyCode == 27) {
        this.sendAction('close');
      }
    });
  }.on('didInsertElement'),

  teardown: function() {
    Ember.$('body').off('keyup');
  }.on('willDestroyElement'),

});
```

**Comment by raycohen** [comment]
That approach can work for many apps.  You can check out https://github.com/yapplabs/ember-key-responder (and the example setup in this project's readme) if you want something more robust

**Comment by samselikoff** [comment]
Ah. I saw this in the readme, but when I glanced at the project I honestly couldn't tell if it was talking about keyboard events. Thanks!
