### ISSUE TITLE
Modal is measured pre-wormhole?

### ISSUE THREAD

**Issue by courajs** [yapplabs/ember-modal-dialog#95]
I was having some issues with modals gettting the wrong padding, and not being centered correctly.
So I put a breakpoint in `positioned-container.js#alignCenter`. I noticed that at this point, when dimension measurements are being made, the element is located in the DOM where the {{#modal-dialog}} component is used (i.e. it has not yet been pulled out into the modal container).

In our case we had a stray rule on divs. But basically, it's being measured in one place in the document, then those measurements are assumed to be accurate when it's placed in a different location in the document.

Is there a technical reason why this is?

**Comment by lukemelia** [comment]
We're using CSS for centering now as of [2.2.0](https://github.com/yapplabs/ember-modal-dialog/releases/tag/v2.2.0). It should avoid this issue.
