### ISSUE TITLE
Container class name bindings

### ISSUE THREAD

**Issue by samselikoff** [yapplabs/ember-modal-dialog#99]
Would be great to be able to bind props to the container-class names:

``` hbs
{{#ted-modal small=true}}
  ...
{{/ted-modal}}
```

``` js
// components/ted-modal/component.js
import ModalDialog from 'ember-modal-dialog/components/modal-dialog';
import Ember from 'ember';

export default ModalDialog.extend({

  overlayClassNames: ['Ted-modal-overlay'],
  containerClassNames: ['Ted-modal'],
  containerClassNameBindings: ['small:Ted-modal--small'],
  translucentOverlay: true,

});
```

This is not possible today, correct?

**Comment by samselikoff** [comment]
Workaround today: 

```hbs
{{#ted-modal container-class='Ted-modal--small'}}
```

but I really like encapsulating this kind of stuff in an API for the component

**Comment by lukemelia** [comment]
I've always been annoyed by this aspect of our API. If you have ideas to improve it, please share. :-)

**Comment by lukemelia** [comment]
I think you could do this by making `containerClassNames` a computed property in your subclass.
